#!/usr/bin/env bash

# Set SLURM options (you should not need to change these)
#SBATCH --job-name=gs                          # Job name
#SBATCH --output=o-%j.out                     # Name for output log file (%j is job ID)
#SBATCH --nodes=1                               # Requesting 1 node and 1 task per node should
#SBATCH --ntasks-per-node=1                     # ensure exclusive access to the node
#SBATCH --cpus-per-task=16                      # Limit the job to specified cores
#SBATCH --partition=gpu-short                   # Use the partition with the GPUs
#SBATCH --time=00:05:00                         # Time limit hrs:min:sec


# Print SLURM envirionment variables
echo "# Job Info ----------------------------"
echo "Job ID: ${SLURM_JOB_ID}"
echo "Node: ${SLURMD_NODENAME}"
echo "Starting: "`date +"%D %T"`

echo -e "\n# Run Results -------------------------"
./project-main

echo yep
# For reference, dump info about the GPUs and processor
# echo -e "\n# CPU Info ----------------------------"
# nvidia-smi
# lscpu